# model settings
embedding_size: 256
hidden_size: 512
latent_size: 256
MLP_neuron_size: 512
rnn_type: "gru"
num_highway_layers: 2
num_enc_layers: 3
num_dec_layers: 3
bidirectional: True

# training settings
learner: adam
learning_rate: 0.001
eval_step: 2
stopping_step: 5
dropout_ratio: 0.5
