# model settings
embedding_size: 300
hidden_size: 500
latent_size: 300
MLP_neuron_size: 400
rnn_type: "gru"
num_highway_layers: 2
num_enc_layers: 2
num_dec_layers: 1
bidirectional: True

# training settings
learner: adam
learning_rate: 0.00005
eval_step: 2
stopping_step: 5
dropout_ratio: 0.5
